### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by NovaPixell** [MherZaqaryan/Bedwars1058-Compass#3]
I have encountered this error. I ask for a correction of the problem.

```
[21:32:00] [Server thread/WARN]: [BedWars1058-Compass] Task #529324 for BedWars1058-Compass v1.4 generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between treenan-4v4 and lobby
	at org.bukkit.Location.distanceSquared(Location.java:456) ~[server.jar:git-NachoSpigot-"39f2882"]
	at org.bukkit.Location.distance(Location.java:439) ~[server.jar:git-NachoSpigot-"39f2882"]
	at club.mher.compass.tasks.ActionBarTask.lambda$getSorted$0(ActionBarTask.java:50) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_292]
	at club.mher.compass.tasks.ActionBarTask.getSorted(ActionBarTask.java:50) ~[?:?]
	at club.mher.compass.tasks.ActionBarTask.getPlayer(ActionBarTask.java:44) ~[?:?]
	at club.mher.compass.tasks.ActionBarTask.run(ActionBarTask.java:32) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[server.jar:git-NachoSpigot-"39f2882"]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [server.jar:git-NachoSpigot-"39f2882"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:796) [server.jar:git-NachoSpigot-"39f2882"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:405) [server.jar:git-NachoSpigot-"39f2882"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:726) [server.jar:git-NachoSpigot-"39f2882"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:619) [server.jar:git-NachoSpigot-"39f2882"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
```

Attached error from BedWars1058:

```
[21:21:14] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to BedWars1058 v21.11.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-NachoSpigot-"39f2882"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[server.jar:git-NachoSpigot-"39f2882"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-NachoSpigot-"39f2882"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:490) ~[server.jar:git-NachoSpigot-"39f2882"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:475) ~[server.jar:git-NachoSpigot-"39f2882"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:393) ~[server.jar:git-NachoSpigot-"39f2882"]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) ~[server.jar:git-NachoSpigot-"39f2882"]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[server.jar:git-NachoSpigot-"39f2882"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:6) ~[server.jar:git-NachoSpigot-"39f2882"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_292]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_292]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-NachoSpigot-"39f2882"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:787) [server.jar:git-NachoSpigot-"39f2882"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:405) [server.jar:git-NachoSpigot-"39f2882"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:726) [server.jar:git-NachoSpigot-"39f2882"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:619) [server.jar:git-NachoSpigot-"39f2882"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.IllegalArgumentException: Cannot measure distance between lobby and treenan-4v4
	at org.bukkit.Location.distanceSquared(Location.java:456) ~[server.jar:git-NachoSpigot-"39f2882"]
	at org.bukkit.Location.distance(Location.java:439) ~[server.jar:git-NachoSpigot-"39f2882"]
	at com.andrei1058.bedwars.listeners.DamageDeathMove.onMove(DamageDeathMove.java:608) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor146.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[server.jar:git-NachoSpigot-"39f2882"]
	... 16 more
```

**Comment by MherZaqaryan** [comment]
Hello, are you using any modified version of BedWars1058? This is not seems to be right!

**Comment by NovaPixell** [comment]
Hi, I use the official latest version. It isn:t custom

**Comment by MherZaqaryan** [comment]
Can you show me your plugins list?

**Comment by andrei1058** [comment]
Disable force-spawn on re-spawning if you ware using Essentials. Otherwhise remove or configure any re-spawn related plugins because players seem to be re-spawning at lobby.

**Comment by NovaPixell** [comment]
> Can you show me your plugins list?

Here: https://github.com/MherZaqaryan/Bedwars1058-Compass/issues/3#issuecomment-993936691

**Comment by NovaPixell** [comment]
> 

I haven't any re-spawn plugin or similar, Essentials too

**Comment by NovaPixell** [comment]
Hi, thhe latest commit fixes this issue?

**Comment by MherZaqaryan** [comment]
This issue is already fixed and will be available on the next update!

**Comment by NovaPixell** [comment]
> This issue is already fixed and will be available on the next update!

Thanks! Can I build my self it?

**Comment by MherZaqaryan** [comment]
> > This issue is already fixed and will be available on the next update!
> 
> Thanks! Can I build my self it?

You can build it yourself anytime, but I do recommend waiting for the next update because it's gonna include other bug fixes too!

**Comment by NovaPixell** [comment]
Ok thanks!Il 15 dic 2021 14:08, Mher Zaqaryan ***@***.***> ha scritto:


This issue is already fixed and will be available on the next update!

Thanks! Can I build my self it?

You can build it yourself anytime, but I do recommend waiting for the next update because it's gonna include other bug fixes too!

**Comment by MherZaqaryan** [comment]
This Issue is already fixed, download it from here:
https://www.spigotmc.org/resources/91537/
https://polymart.org/resource/1660/
